# Generated by Django 5.0 on 2024-05-20 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=15)),
                ('val_id', models.CharField(max_length=75)),
                ('card_type', models.CharField(max_length=150)),
                ('store_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_no', models.CharField(blank=True, max_length=55)),
                ('bank_tran_id', models.CharField(blank=True, max_length=155)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('card_issuer', models.CharField(blank=True, max_length=255)),
                ('card_brand', models.CharField(blank=True, max_length=15)),
                ('card_issuer_country', models.CharField(blank=True, max_length=55)),
                ('card_issuer_country_code', models.CharField(blank=True, max_length=55)),
                ('currency_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verify_sign', models.CharField(blank=True, max_length=155)),
                ('verify_sign_sha2', models.CharField(blank=True, max_length=255)),
                ('risk_level', models.CharField(blank=True, max_length=15)),
                ('risk_title', models.CharField(blank=True, max_length=25)),
                ('courses', models.ManyToManyField(blank=True, to='course.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
